clear all
close all
clc


imagesList_T1_synt = [ ...
"AddNoiseDialog.bmp" ...
"AnisoDialogBox.bmp" ...
]

imagesList_T1 = [...
"05_512x512.bmp" ...
"14_512x512.bmp" ...
"anemone.bmp" ...
"atlas1k_512x512.bmp" ...
"baboon_512x512.bmp" ...
"bangko_13_512x512.bmp" ...
"barb_512x512.bmp" ...
"boats_512x512.bmp" ...
"cDNA1.bmp" ...
"crow64_512x512.bmp" ...
"fruits_512x512.bmp" ...
"frymire_512x512.bmp" ...
"girls_512x512.bmp" ...
"gold_512x512.bmp" ...
"INDSTR26.bmp" ...
"iptcte~3.bmp" ...
"kodakBus.bmp" ...
"KODIE_512x512.bmp" ...
"kodim07.bmp" ...
"kodim23_512x512.bmp" ...
"lena_512x512.bmp" ...
"lokomot_01_512x512.bmp" ...
"lokomot_02_512x512.bmp" ...
"METROCHI.bmp" ...
"monarch_512x512.bmp" ...
"Motiv017_01_512x512.bmp" ...
"Motiv017_02_512x512.bmp" ...
"newyork_512x512.bmp" ...
"papuga_01_512x512.bmp" ...
"party_4s01_512x512.bmp" ...
"party_4s_512x512.bmp" ...
"peppers3_512x512.bmp" ...
"picnic_4s_01_512x512.bmp" ...
"picnic_4s_02_512x512.bmp" ...
"picnic_4s_03_512x512.bmp" ...
"probka5-orig.bmp" ...
"psal309k_512x512.bmp" ...
"satelv_512x512.bmp" ...
"sydney_01_512x512.bmp" ...
"sydney_02_512x512.bmp" ...
"watch01_512x512.bmp" ...
"watch02_512x512.bmp" ...
];


imagesList_T2 = [...
"img_001.bmp" ...
"img_002.bmp" ...
"img_003.bmp" ...
"img_004.bmp" ...
"img_005.bmp" ...
"img_006.bmp" ...
"img_007.bmp" ...
"img_008.bmp" ...
"img_009.bmp" ...
"img_010.bmp" ...
"img_011.bmp" ...
"img_012.bmp" ...
"img_013.bmp" ...
"img_014.bmp" ...
"img_015.bmp" ...
"img_016.bmp" ...
"img_017.bmp" ...
"img_018.bmp" ...
"img_019.bmp" ...
"img_020.bmp" ...
"img_021.bmp" ...
"img_022.bmp" ...
"img_023.bmp" ...
];

imagesList_T3 = [...
"bird.tiff" ...
"bookstand.tiff" ...
"candlestick.tiff" ...
"ceramic_dog.tiff" ...
"dog.tiff" ...
"fabric1.tiff" ...
"fabric2.tiff" ...
"floor.tiff" ...
"flowerpots.tiff" ...
"frame.tiff" ...
"grill1.tiff" ...
"grill2.tiff" ...
"grill3.tiff" ...
"herbs.tiff" ...
"houses.tiff" ...
"kitchen.tiff" ...
"leaflet.tiff" ...
"monitor.tiff" ...
"mug.tiff" ...
"page.tiff" ...
"painting.tiff" ...
"pathway.tiff" ...
"pear.tiff" ...
"pens.tiff" ...
"printed_text.tiff" ...
"residential.tiff" ...
"rock.tiff" ...
"sand.tiff" ...
"sensor1.tiff" ...
"sensor2.tiff" ...
"signature.tiff" ...
"socket.tiff" ...
"statuette.tiff" ...
"strawberry.tiff" ...
"tall_ship.tiff" ...
"tanks.tiff" ...
"texture1.tiff" ...
"tomatoes.tiff" ...
"tree.tiff" ...
"villige2.tiff" ...
"wall.tiff" ...
"water.tiff" ...
"wicker.tiff" ...
"wine.tiff" ...
"wooden_hut1.tiff" ...
"wooden_hut2.tiff" ...

];


imagesList = imagesList_T1_synt
for i = [1:max(size(imagesList))]
    targetFolder = '..\convertedImg\T1_s'+ string(i);
    sourceFile = '..\obrazy\TestImages1\dialogs\' + imagesList(i)
    try
        ConvertFormat(sourceFile ,targetFolder, 'image');
    catch
        warning('error while converting ' + sourceFile);
    end
end


% imagesList = imagesList_T1
% for i = [1:max(size(imagesList))]
%     targetFolder = '..\convertedImg\T1_'+ string(i);
%     sourceFile = '..\obrazy\TestImages1\color\' + imagesList(i)
%     try
%         ConvertFormat(sourceFile ,targetFolder, 'image');
%     catch
%         warning('error while converting ' + sourceFile);
%     end
% end
% 
% 
% 
% imagesList = imagesList_T2
% for i = [1:max(size(imagesList))]
%     targetFolder = '..\convertedImg\T2_'+ string(i);
%     sourceFile = '..\obrazy\TestImages2\' + imagesList(i)
%     try
%         ConvertFormat(sourceFile ,targetFolder, 'image');
%     catch
%         warning('error while converting ' + sourceFile);
%     end
% end


% imagesList = imagesList_T3
% for i = [1:max(size(imagesList))]
%     targetFolder = '..\convertedImg\T3_'+ string(i);
%     sourceFile = '..\obrazy\TestImages3\' + imagesList(i)
%     %try
%         ConvertFormat(sourceFile ,targetFolder, 'image');
%     %catch
%         warning('error while converting ' + sourceFile);
%     %end
% end


