
Foto = [...
"..\Obrazy\Bayer\CFA_sRGB\cienkopisy_srgb_CFA.png"  ,"..\step1_demosaic\CFA_sRGB\cienkopisy_srgb_CFA.png";...    
"..\Obrazy\Bayer\CFA_sRGB\IMG_0016_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0016_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_0018_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0018_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_0022_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0022_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_003_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_003_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_006_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_006_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_007_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_007_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_008_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_008_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_009_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_009_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_010_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_010_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_011_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_011_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_012_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_012_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_013_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_013_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_014_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_014_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_015_srgb_CFA.png"     ,"..\step1_demosaic\CFA_sRGB\IMG_015_srgb_CFA.png"   ;... 
"..\Obrazy\Bayer\CFA_sRGB\IMG_0440_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0440_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_0669_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0669_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_0670_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0670_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_0674_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_0674_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7066_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7066_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7067_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7067_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7068_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7068_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7069_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7069_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7072_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7072_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7073_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7073_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7074_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7074_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7076_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7076_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7078_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7078_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7084_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7084_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7085_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7085_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7107_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7107_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7109_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7109_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7111_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7111_srgb_CFA.png"  ;...  
"..\Obrazy\Bayer\CFA_sRGB\IMG_7116_srgb_CFA.png"    ,"..\step1_demosaic\CFA_sRGB\IMG_7116_srgb_CFA.png"  ;...  
]

mosaicPattern = "bggr"



for foto = Foto'
    
    disp ( foto )

    [A, map] = imread(foto(1));

    A1 = demosaic(A, mosaicPattern);

    imwrite(A1, foto(2) );
    
    
end







